### ISSUE TITLE
Not finding any commands

### ISSUE THREAD

**Issue by swilson72** [kevinkm/get_rm_command#1]
I have set this up, and it seems to almost work, but it's not finding any commands.

I am using the learn command function in home assistant, and when I go back and view states, I see the received packets.

But when I run rm2.py I just get several lines containing just [], and then "0  commands are done!"

Here is the relevant portion of my configuration.yaml file:  
switch:

  - platform: broadlink
    host: 192.168.1.6
    mac: 34:EA:34:E7:EB:BE
    name: "example"
    timeout: 30
    type: rm2
    switches:
      fan:
        command_on: ""
        command_off: ""

Am I supposed to edit anything in foxgroup.yaml?  foxscript.yaml is just an empty file, should something have been written to this?

**Comment by kevinkm** [comment]
Oh I see, you should download the configuration.yaml I give.

and go to visit youtube for HOWTO: https://www.youtube.com/watch?v=AWA15OI-sfw&feature=youtu.be

then.......

~$ python3 rm2.py

**Comment by jbcole05** [comment]
I am stumped. Am getting the following output when I run rm2.py. Any suggestions?
--------
THE PROGRAM JUST FOR NEWBIEs


Already stay at the directory of home-assistant!

You may have group name.


Get your broadlink ip is: 192.168.100.154
Traceback (most recent call last):
  File "rm2.py", line 101, in <module>
    switch_number = check_foxgroup_num()
  File "rm2.py", line 33, in check_foxgroup_num
    a = re.findall( r'(?<=script.fox_controls_).*', line[-1] )
IndexError: list index out of range
